version: '3.8'
services:
  blank_creatro_vue:
    image: blank_creatro_vue
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=${SERVER_IP}
      - JAVA_PORT=${JAVA_PORT}
      - VUE_IP=${VUE_IP}
      - VUE_PORT=${VUE_PORT}
      - VITE_JAVA_IP=${VITE_JAVA_IP}
      - VITE_JAVA_PORT=${VITE_JAVA_PORT}
      - PY_IP=${PY_IP}
      - PY_PORT=${PY_PORT}
    ports:
      - "5173:5173"

