version: '3.8'
services:
  blank_creator_java:
    image: springboot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "5007:5007"

  blank_creator_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
    ports:
      - "5432:5432"
