version: '3.8'
services:
  blank_creator_java:
    image: springboot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SERVER_IP=${SERVER_IP}
        - JAVA_PORT=${JAVA_PORT}
        - VUE_IP=${VUE_IP}
        - VUE_PORT=${VUE_PORT}
        - PY_IP=${PY_IP}
        - PY_PORT=${PY_PORT}       
    ports:
      - "${JAVA_PORT}:${JAVA_PORT}"


  blank_creator_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
    ports:
      - "5432:5432"
    volumes:
      - ~/db_data:/var/lib/postgresql/data
