version: '3.8'

services:
  py:
    image: gen_blank_py:latest
    container_name: gen_blank_py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"  # Порт, который будет использоваться Flask
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    environment:
      - FLASK_ENV=development  # Устанавливаем переменную окружения для режима разработки
