version: '3.8'

services:
  py:
    image: gen_blank_py:latest
    container_name: gen_blank_py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PY_PORT}:${PY_PORT}"
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    environment:
      - FLASK_ENV=development  # Устанавливаем переменную окружения для режима разработки
      - SERVER_IP=${SERVER_IP}
      - JAVA_PORT=${JAVA_PORT}
      - VUE_IP=${VUE_IP}
      - VUE_PORT=${VUE_PORT}
      - VITE_JAVA_IP=${VITE_JAVA_IP}
      - VITE_JAVA_PORT=${VITE_JAVA_PORT}
      - PY_IP=${PY_IP}
      - PY_PORT=${PY_PORT}
