# name: Run Tests on Master Commit

# on:
#   push:
#     branches:
#       - master 

# jobs:
#   test:
#     runs-on: ubuntu-latest  

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2  

#       - name: Set up JDK
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'temurin'
#           java-version: '11'  

      
#       - name: Stop containers
#         run: ./stop.sh 

#       - name: Start containers
#         run: mvn test  
