name: Run Tests on Master Commit

on:
  push:
    branches:
      - master  # Запускать тесты только при коммите в master

jobs:
  test:
    runs-on: ubuntu-latest  # Используем виртуальную машину Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'  # Укажите нужную версию JDK (например, 11 или 17)

      
      - name: Build with Maven
        run: cd backend && mvn clean install  # Компилируем проект и собираем зависимости

      - name: Run tests
        run: mvn test  # Запуск тестов
